helmCharts:
  - name: kannika
    includeCRDs: false
    valuesInline:
      global:
        kubernetes:
          namespace: kannika-data
      kubeVersionOverride: 1.30.0
    releaseName: kannika
    version: 0.15.2
    repo: oci://quay.io/kannika/charts
